name: Build
on:
  push:
jobs:
  sast:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      
      - name: Dependencies
        run: |
          pip3 install cpplint
      
      - name: Static Analysis
        run: |
          cpplint --recursive src/
      
      

      
      
          