name: Build
on:
  push:
jobs:
  sast:
    name: SAST
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      
      - name: Dependencies
        run: |
          pip3 install cpplint
          sudo apt-get install -y cppcheck
      
      - name: Static Analysis
        run: |
          cpplint --recursive src/ include/ tests/examples/
          cppcheck --enable=all --suppress=missingInclude --suppress=missingIncludeSystem src/ include/ tests/ examples/
      
      - name: Static Analysis Misra
        run: |
          cppcheck --addon=cpplint_config/misra.json  src include examples

      
          